### ISSUE TITLE
Update regex

### ISSUE THREAD

**Issue by miccheng** [sophi-li/scale-conversion#1]
Try this instead?

```
/(?<qty>[^\s]+) (?<scale>[tablespoon|gram|cup|tsp|tbs]+)(\sof\s|\s)(?<ingredient>[\s\S]+)/
```

Reference: https://github.com/sophi-li/scale-conversion/blob/d5abe8bf1a04a2b36a1146b0585865e652b2b6cd/app.js#L65

**Comment by sophi-li** [comment]
Thanks, it's so close! It doesn't capture the "1" in "1 1/2 cup butter milk" like in the screenshot. And I'm not sure why that is. And it also errors out when it hits something like "1 medium egg". I believe it errors out at "1 medium egg" because the second group` (?<scale>[tablespoon|gram|cup|tsp|tbs]+)(\sof\s|\s) `doesn't catch the "medium". 

To capture "1 medium egg", I was able to use `let regex = /(?<qty>[^s*|^\s]*) (?<scale>[\w|tablespoon|gram|cup|tsp|tbs]+)(\sof\s|\s)(?<ingredient>[\s\S]+)/;`. But this one still doesn't capture the "1" in "1 1/2 cup butter milk". 

![Screen Shot 2020-04-22 at 9 39 51 PM](https://user-images.githubusercontent.com/26865116/80059900-08014e00-84e2-11ea-8ddf-5841a57596cc.png)
